package view;

import model.Professor;
import repository.ProfessorRepository;
import repository.ProfessorRepositoryImpl;
import service.ProfessorService;
import service.ProfessorServiceImpl;
import service.exception.ValidacaoException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 * Tela de edição de professores do sistema.
 * <p>
 * Esta interface gráfica permite carregar, visualizar e alterar
 * os dados de um professor previamente cadastrado. O formulário
 * é preenchido automaticamente com as informações do professor
 * selecionado e, após edição, os dados são validados e enviados
 * ao serviço para atualização.
 * </p>
 * 
 * <p>
 * Utiliza um {@link ProfessorService} para regras de negócio e
 * persistência, garantindo que dados inválidos não sejam salvos.
 * Máscaras também são aplicadas para padronização de CPF,
 * contato e salário.
 * </p>
 */

public class EditarProfessor extends javax.swing.JFrame {

    private final ProfessorService professorService;
    private int idProfessor;

    /**
     * Construtor da tela de edição de professor.
     * <p>
     * Inicializa repositório, serviço, componentes gráficos, formata
     * campos e preenche automaticamente o formulário com os dados
     * do professor selecionado na tela de gerenciamento.
     * </p>
     *
     * @throws ParseException caso ocorra erro ao aplicar máscaras.
     */

    public EditarProfessor() throws java.text.ParseException {
        ProfessorRepository professorRepository = new ProfessorRepositoryImpl();
        this.professorService = new ProfessorServiceImpl(professorRepository);

        initComponents();
        formatarCampos();
        preencheCampos();
        getRootPane().setDefaultButton(this.bConfirmar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents

    /**
     * Inicializa os componentes gráficos da interface.
     *
     * <p>
     * Este método é gerado automaticamente pelo editor visual do NetBeans.
     * Alterações manuais não são recomendadas.
     * </p>
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        campus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        bConfirmar = new javax.swing.JButton();
        titulo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cpfFormatado = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        salarioFormatado = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        idade = new javax.swing.JTextField();
        contatoFormatado = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Professor");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Professor");

        campus.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "-", "Continente", "Dib Mussi", "Ilha", "Pedra Branca", "Trajano", "Tubarão" }));
        campus.setName(""); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nome:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Campus:");

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bConfirmar.setText("Confirmar");
        bConfirmar.setToolTipText("ENTER");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        titulo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "-", "Graduação", "Especialização", "Mestrado", "Doutorado" }));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Título:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Idade:");

        jLabel9.setText("CPF:");

        jLabel5.setText("Salário:");

        jLabel7.setText("Contato:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406,
                                                        Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel8))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(bConfirmar,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        108,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(66, 66, 66)
                                                                                .addComponent(bCancelar,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        108,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(titulo,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        282,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(idade,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                108,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(jLabel5)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(salarioFormatado,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                104,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel9))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(nome)
                                                                        .addComponent(campus, 0, 282, Short.MAX_VALUE)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(cpfFormatado)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(jLabel7)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(contatoFormatado,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                104,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cpfFormatado, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(contatoFormatado, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8)
                                                .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(salarioFormatado, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Aplica máscaras de formatação aos campos CPF, Contato e Salário.
     *
     * @throws ParseException caso alguma máscara não possa ser aplicada.
     */

    private void formatarCampos() throws java.text.ParseException {
        try {
            MaskFormatter mask = new MaskFormatter("###.###.###-##");
            mask.install(cpfFormatado);
            MaskFormatter mask2 = new MaskFormatter("(##) # ####-####");
            mask2.install(contatoFormatado);
            MaskFormatter mask3 = new MaskFormatter("R$#####");
            mask3.install(salarioFormatado);
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao formatar campos", "ERRO", JOptionPane.ERROR);
        }
    }

    /**
     * Remove os dois últimos caracteres da string de salário formatado.
     * <p>
     * Utilizado para ajustar o valor antes da conversão numérica.
     * </p>
     *
     * @param input salário no formato texto com máscara.
     * @return string sem os dois últimos caracteres.
     */
    private String editSalario(String input) {
        String str = "";

        for (int i = 0; i < input.length() - 2; i++) {
            str += input.charAt(i) + "";
        }

        return str;
    }

    /**
     * Preenche o formulário com os dados do professor selecionado
     * na tela de gerenciamento.
     * <p>
     * Localiza o professor pelo ID, seta valores nos campos de texto,
     * aplica seleção correta nos combos e exibe mensagem caso o registro
     * não seja encontrado.
     * </p>
     */
    private void preencheCampos() {
        try {
            this.idProfessor = Integer.parseInt(GerenciaProfessores.listaDados[7]);
            Professor professor = professorService.buscarPorId(this.idProfessor);

            if (professor == null) {
                JOptionPane.showMessageDialog(rootPane, "Professor não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                this.dispose();
                return;
            }

            String[] arrayCampus = { "-",
                    "Continente",
                    "Dib Mussi",
                    "Ilha",
                    "Pedra Branca",
                    "Trajano",
                    "Tubarão" };
            String[] arrayTitulo = { "-",
                    "Graduação",
                    "Especialização",
                    "Mestrado",
                    "Doutorado" };

            int indexCampus = 0;
            int indexTitulo = 0;

            for (int i = 0; i < 7; i++) {
                if (professor.getCampus().equalsIgnoreCase(arrayCampus[i])) {
                    indexCampus = i;
                }
            }

            for (int j = 0; j < 5; j++) {
                if (professor.getTitulo().equalsIgnoreCase(arrayTitulo[j])) {
                    indexTitulo = j;
                }
            }

            this.nome.setText(professor.getNome());
            this.idade.setText(String.valueOf(professor.getIdade()));
            this.campus.setSelectedIndex(indexCampus);
            this.cpfFormatado.setText(professor.getCpf());
            this.contatoFormatado.setText(professor.getContato());
            this.titulo.setSelectedIndex(indexTitulo);
            this.salarioFormatado.setText(String.valueOf((int) professor.getSalario()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar dados do professor.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * Ação executada ao clicar no botão Confirmar.
     * <p>
     * Coleta os valores do formulário, realiza validações iniciais,
     * monta um objeto {@link Professor} com os dados editados
     * e envia para o serviço atualizar no banco.
     * </p>
     *
     * @param evt evento de clique do botão Confirmar.
     */

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bConfirmarActionPerformed
        try {
            String[] arrayCampus = { "-",
                    "Continente",
                    "Dib Mussi",
                    "Ilha",
                    "Pedra Branca",
                    "Trajano",
                    "Tubarão" };
            String[] arrayTitulo = { "-",
                    "Graduação",
                    "Especialização",
                    "Mestrado",
                    "Doutorado" };

            int idade;
            try {
                idade = Integer.parseInt(this.idade.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Idade deve ser um número válido.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String campus = arrayCampus[this.campus.getSelectedIndex()];
            String cpf = this.cpfFormatado.getText();
            String contato = this.contatoFormatado.getText();
            String titulo = arrayTitulo[this.titulo.getSelectedIndex()];

            String salarioFormatado = professorService.validarFormatado(this.salarioFormatado.getText());
            double salario = Double.parseDouble(salarioFormatado);

            Professor professor = new Professor();
            professor.setId(this.idProfessor);
            professor.setNome(this.nome.getText());
            professor.setIdade(idade);
            professor.setCampus(campus);
            professor.setCpf(cpf);
            professor.setContato(contato);
            professor.setTitulo(titulo);
            professor.setSalario(salario);

            professorService.atualizar(professor);

            JOptionPane.showMessageDialog(rootPane, "Professor alterado com sucesso!", "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (ValidacaoException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Salário deve ser um número válido.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro inesperado. Contate o suporte.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_bConfirmarActionPerformed

    /**
     * Ação do botão Cancelar.
     * Fecha a tela sem salvar alterações.
     *
     * @param evt evento de clique do botão Cancelar.
     */

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }// GEN-LAST:event_bCancelarActionPerformed

    /**
     * Método principal para abrir a interface de edição de professor.
     *
     * @param args argumentos de linha de comando (não utilizados).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProfessor.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EditarProfessor().setVisible(true);
                } catch (java.text.ParseException ex) {
                    Logger.getLogger(EditarProfessor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bConfirmar;
    private javax.swing.JComboBox<String> campus;
    private javax.swing.JFormattedTextField contatoFormatado;
    private javax.swing.JFormattedTextField cpfFormatado;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nome;
    private javax.swing.JFormattedTextField salarioFormatado;
    private javax.swing.JComboBox<String> titulo;
    // End of variables declaration//GEN-END:variables
}
