package view;

import model.Aluno;
import repository.AlunoRepository;
import repository.AlunoRepositoryImpl;
import service.AlunoService;
import service.AlunoServiceImpl;
import service.exception.ValidacaoException;
import javax.swing.JOptionPane;

public class EditarAluno extends javax.swing.JFrame {
    
    /**
     * Janela de edição dos dados de um aluno.
     *
     * <p>
     * Esta interface permite alterar nome, idade, curso e fase de um aluno já
     * cadastrado no sistema. Ao ser carregada, a tela busca os dados do aluno
     * selecionado e preenche automaticamente os campos para edição.
     * </p>
     *
     * <p>
     * Toda validação e atualização é delegada ao {@link AlunoService}.
     * </p>
     */

    private final AlunoService alunoService;
    private int idAluno;

    /**
     * Construtor da tela de edição de alunos.
     *
     * <p>
     * Inicializa componentes da interface, prepara o serviço de alunos e
     * carrega os dados do aluno selecionado na tabela da tela GerenciaAlunos.
     * </p>
     */

    public EditarAluno() {
        AlunoRepository alunoRepository = new AlunoRepositoryImpl();
        this.alunoService = new AlunoServiceImpl(alunoRepository);

        initComponents();
        preencheCampos();
        getRootPane().setDefaultButton(this.bConfirmar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents

    /**
     * Inicializa os componentes gráficos da interface.
     *
     * <p>
     * Este método é gerado automaticamente pelo editor visual do NetBeans.
     * Alterações manuais não são recomendadas.
     * </p>
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        curso = new javax.swing.JComboBox<>();
        fase = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        bConfirmar = new javax.swing.JButton();
        idade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Aluno");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Aluno");

        curso.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "-", "Administração", "Análise e Desenvolvimento de Sistemas", "Arquitetura e Urbanismo",
                        "Ciências Contábeis", "Ciências da Computação", "Design", "Design de Moda",
                        "Relações Internacionais", "Sistemas de Informação" }));
        curso.setName(""); // NOI18N

        fase.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "1ª", "2ª", "3ª", "4ª", "5ª", "6ª", "7ª", "8ª", "9ª", "10ª" }));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Curso:");

        jLabel4.setText("Idade:");

        jLabel5.setText("Fase:");

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bConfirmar.setText("Confirmar");
        bConfirmar.setToolTipText("ENTER");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nome)
                                        .addComponent(curso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 123,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fase, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(66, 66, 66)
                                                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(37, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fase, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Preenche os campos da tela com os dados do aluno selecionado.
     *
     * <p>
     * Obtém o ID da linha selecionada em {@code GerenciaAlunos},
     * busca o aluno correspondente no banco de dados e ajusta os campos
     * visuais (nome, idade, curso e fase) para edição.
     * </p>
     *
     * <p>
     * Caso o aluno não seja encontrado, a tela é fechada automaticamente.
     * </p>
     */

    private void preencheCampos() {
        try {
            this.idAluno = Integer.parseInt(GerenciaAlunos.listaDados2[0]);
            Aluno aluno = alunoService.buscarPorId(this.idAluno);

            if (aluno == null) {
                JOptionPane.showMessageDialog(rootPane, "Aluno não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                this.dispose();
                return;
            }

            String[] arrayCursos = { "-",
                    "Administração",
                    "Análise e Desenvolvimento de Sistemas",
                    "Arquitetura e Urbanismo",
                    "Ciências Contábeis",
                    "Ciências da Computação",
                    "Design",
                    "Design de Moda",
                    "Relações Internacionais",
                    "Sistemas de Informação" };
            int[] arrayFases = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };

            int indexCursos = 0;
            int indexFases = 0;

            for (int i = 0; i < 10; i++) {
                if (aluno.getCurso().equalsIgnoreCase(arrayCursos[i])) {
                    indexCursos = i;
                }
            }

            for (int i = 0; i < 10; i++) {
                if (aluno.getFase() == arrayFases[i]) {
                    indexFases = i;
                }
            }

            this.nome.setText(aluno.getNome());
            this.idade.setText(String.valueOf(aluno.getIdade()));
            this.curso.setSelectedIndex(indexCursos);
            this.fase.setSelectedIndex(indexFases);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar dados do aluno.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

        /**
     * Ação executada ao confirmar a edição.
     *
     * <p>
     * Valida os campos preenchidos pelo usuário,
     * cria um objeto {@link Aluno} com os novos dados
     * e solicita ao serviço que atualize o registro no banco.
     * </p>
     *
     * @param evt evento de clique no botão "Confirmar".
     */


    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bConfirmarActionPerformed
        try {
            String[] arrayCursos = { "-",
                    "Administração",
                    "Análise e Desenvolvimento de Sistemas",
                    "Arquitetura e Urbanismo",
                    "Ciências Contábeis",
                    "Ciências da Computação",
                    "Design",
                    "Design de Moda",
                    "Relações Internacionais",
                    "Sistemas de Informação" };
            int[] arrayFases = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };

            int idade;
            try {
                idade = Integer.parseInt(this.idade.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Idade deve ser um número válido.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            String curso = arrayCursos[this.curso.getSelectedIndex()];
            int fase = arrayFases[this.fase.getSelectedIndex()];

            Aluno aluno = new Aluno();
            aluno.setId(this.idAluno);
            aluno.setNome(this.nome.getText());
            aluno.setIdade(idade);
            aluno.setCurso(curso);
            aluno.setFase(fase);

            alunoService.atualizar(aluno);

            JOptionPane.showMessageDialog(rootPane, "Aluno alterado com sucesso!", "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (ValidacaoException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro inesperado. Contate o suporte.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_bConfirmarActionPerformed

        /**
     * Ação executada ao pressionar o botão "Cancelar".
     *
     * <p>
     * Fecha a janela sem salvar alterações.
     * </p>
     *
     * @param evt evento do botão.
     */


    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }// GEN-LAST:event_bCancelarActionPerformed

        /**
     * Método principal para execução isolada da tela.
     *
     * @param args argumentos de linha de comando.
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bConfirmar;
    private javax.swing.JComboBox<String> curso;
    private javax.swing.JComboBox<String> fase;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nome;
    // End of variables declaration//GEN-END:variables
}
